name: Delete Message

on:
  repository_dispatch:
    types: [lihat_pesan]

jobs:
  delete-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete specific file
        run: |
          rm -f delete.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Delete pesan.txt after being viewed" || echo "No changes to commit"
          git push
          
