name: Delete Message

on:
  repository_dispatch:
    types: [delete_message]

jobs:
  delete_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Remove Message File
        run: |
          rm -f message.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Delete message.txt after viewing"
          git push
